using System;
using System.Collections;
using System.IO;
using Siemens.Engineering;
using Siemens.Engineering.HW;
using Siemens.Engineering.Cax;
using System.Collections.Generic;

namespace HwGen
{
  class Program
  {

    static void Main(string[] args)
    {

      string filename = @"";
      string path_to_file = @"";
      string project_path = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
      DateTime dateTime = DateTime.Now;
      string date = dateTime.Year.ToString() + dateTime.Month.ToString().PadLeft(2,'0') + dateTime.Day.ToString().PadLeft(2, '0') + dateTime.Hour.ToString().PadLeft(2, '0') + dateTime.Minute.ToString().PadLeft(2, '0');     
      string project_name = @"AutogeneratedProject_"+date;
      // Handling arguments
      foreach (string key in args)
      {
        switch (key)
        {
          //Input file is AML
          case "-a":
            path_to_file = GetArgumentValue(args, key);
            filename = Path.GetFileName(path_to_file);
            
            if (!CheckFile(path_to_file, ".aml", true))
            {
              Environment.Exit(1);
            } else
            {
              ImportFromAML(project_name, @project_path, path_to_file);
            }
            break;
          //Input file is CSV
          case "-c":
            path_to_file = GetArgumentValue(args, key);
            if (!CheckFile(path_to_file, ".csv", true))
            {
              Environment.Exit(1);
            }
            else
            {
              ImportFromCSV(project_name, project_path, path_to_file);
            }
            break;
          //Input file is JSON
          case "-j":
            path_to_file = GetArgumentValue(args, key);
            if (!CheckFile(path_to_file, ".json", true))
            {
              Environment.Exit(1);
            }
            break;
          default:
            break;
        }

      }

  

      // End of handling arguments
      
      Console.WriteLine("Press any key to close application!");
      Console.ReadKey();
    }

    static string GetArgumentValue(string[] args, string arg)
    {
      string argument_value = "";
      IEnumerator args_enum = args.GetEnumerator();
      while (args_enum.MoveNext())
      {

        if (args_enum.Current.ToString() == arg)
        {
          args_enum.MoveNext();
          argument_value = args_enum.Current.ToString();
          break;
        }
      }
      return argument_value;

    }

    // checking a file
    static bool CheckFile(string path_to_file, string extension, bool checkExist)
    {
      string filename = Path.GetFileName(path_to_file);
      if (checkExist)
      {
        if (!new FileInfo(path_to_file).Exists)
        {
          Console.WriteLine("File does not exist!");
          Console.ReadKey();
          return false;
        }
      }
      if(Path.GetExtension(filename) != extension)
      {
        Console.WriteLine("Wrong file extension!");
        Console.ReadKey();
        return false;

      } 
        return true;
    }


    static void ImportFromAML(string project_name, string project_path, string aml_file_name)
    {
      Console.WriteLine("Connecting to TIA Portal...");
      using (TiaPortal tiaPortal = new TiaPortal(TiaPortalMode.WithoutUserInterface))
      {
        if (tiaPortal != null)
        {
        Console.WriteLine("Connection is OK!");
        Console.WriteLine("Creating Project...");
        Project project = CreateProject(tiaPortal, project_name, project_path);
        Console.WriteLine("The project is created!");
        Console.WriteLine("Connecting to CAX Provider...");
        CaxProvider caxProvider = project.GetService<CaxProvider>();
        
        FileInfo amlFileInfo = new FileInfo(Path.GetFullPath(aml_file_name));
        FileInfo logFileInfo = new FileInfo(Path.GetTempPath() + Path.GetFileNameWithoutExtension(aml_file_name) + ".log");
          Console.WriteLine(logFileInfo.ToString());
        if (caxProvider != null)
        {
            Console.WriteLine("Connection to CAX Provider is OK!");
            Console.WriteLine("Importing AML to the project... It might take a while. Please wait!");
            try
            { caxProvider.Import(amlFileInfo, logFileInfo, CaxImportOptions.RetainTiaDevice);
            }
            catch(Exception e)
            {
              Console.WriteLine("Error until import: {0}", e.ToString());
              Console.ReadKey();
              Environment.Exit(3);
            }

            Console.WriteLine("Import is done!");
          }
          Console.WriteLine("Saving project...");
          project.Save();
          Console.WriteLine("Save OK!");
          Console.WriteLine("Closing project...");
          project.Close();
          Console.WriteLine("Project closed!");
          Console.WriteLine("Disconnecting from TIA Portal...");
          tiaPortal.Dispose();
          Console.WriteLine("TIA Portal disconnected!");
        }
      }
    }

    static Project CreateProject(TiaPortal tiaPortal, string project_name, string project_path)
    {

      DirectoryInfo projectDirectory = new DirectoryInfo(project_path);
      try
      {
        Project project = tiaPortal.Projects.Create(@projectDirectory, project_name);
        return project;
      } catch (Exception e)
      {
        Console.WriteLine("Could not create project! Error: {0}", e.ToString());
        Console.ReadKey();
        Environment.Exit(2);
      }
      return null;




    }

    static void ImportFromCSV(string project_name, string project_path, string csv_file_name)
    {
      string[] raw_lines = { };
      string[] headers;
      string[] devices_prop; 
      List<HWDevice> device_list = null;
      DeviceComposition devices;
      
      try
      {
        raw_lines = File.ReadAllLines(csv_file_name);
        string[] device_lines = new string[raw_lines.Length - 1];
        Console.WriteLine(raw_lines.Length);
        Console.ReadKey();
        headers = raw_lines[0].Split(',');
        Array.Copy(raw_lines, 1, device_lines, 0, raw_lines.Length-1);
        Console.WriteLine(device_lines.Length);

        foreach (string line in device_lines)
        {
          Console.WriteLine(line);

          string[] properties = line.Split(',');
          string group = properties[0];
          string field = properties[1];
          string name = properties[2];
          string article_number = properties[3];
          string address_range = properties[4];
          string comment = properties[5];

          device_list.Add(new HWDevice(group, field, name, article_number, address_range, comment));
        }
      }
      catch(Exception e)
      {
        Console.WriteLine("{0}",e.ToString());
        Console.ReadKey();
        Environment.Exit(5);
        
      }

      Console.ReadKey();
      Environment.Exit(5);




      Console.WriteLine("Connecting to TIA Portal...");
      using (TiaPortal tiaPortal = new TiaPortal(TiaPortalMode.WithoutUserInterface))
      {
        if (tiaPortal != null)
        {
          Console.WriteLine("Connection is OK!");
          Console.WriteLine("Creating Project...");
          Project project = CreateProject(tiaPortal, project_name, project_path);
          if(project!= null)
          {
            Console.WriteLine("The project is created!");
            Console.WriteLine("Adding devices...");
            foreach (HWDevice device in device_list)
            {
              try
              {
                CreateDevice(project, device.group + device.field + device.name, device.article_number);
              }
              catch(Exception e)
              {
                Console.WriteLine("Can't add device {0}:{1}", device.group + device.field + device.name, e.ToString());
              }

              Console.WriteLine("Device {0} added!", device.group + device.field + device.name);
            }
            Console.WriteLine("All devices added!");
            Console.WriteLine("Saving project...");
            project.Save();
            Console.WriteLine("Save OK!");
            Console.WriteLine("Closing project...");
            project.Close();
            Console.WriteLine("Project closed!");
          }
          
          Console.WriteLine("Disconnecting from TIA Portal...");
          tiaPortal.Dispose();
          Console.WriteLine("TIA Portal disconnected!");
        }
      }
    }

    static Device CreateDevice(Project project, string device_name, string article_number)
    {
      try
      {
        Device device = project.Devices.Create(article_number, device_name);
        return device;
      } catch (Exception e)
      {
        Console.WriteLine("Could not create device! Error: {0}", e.ToString());
        Console.ReadKey();
        Environment.Exit(6);
      }
      return null;
    }
  }
  
  class HWDevice
  {
    public string field;
    public string name;
    public string article_number;
    public string address_range;
    public string comment;
    public string group;

    public HWDevice(string group, string device_field, string device_name, string device_article_number, string device_address_range, string device_comment)
    {
      field = device_field;
      name = device_name;
      article_number = device_article_number;
      address_range = device_address_range;
      comment = device_comment;
    }

  }
   

}
